// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "0b4107e573cf68c61af1d57560bb1128"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"012ad0df3dead178c5e342799d91280a": "1f8b08000000000000ffec58b16edb3010ddf51504d331a9daa980e72e053a1428d0a5c8c058679b094db1c7630ab7f0bf17922d959448caaeed0c75960ca4efbde3ddbb2732bf0bc6f81b3b5fc15af019e32b22332bcb475bebbbddeadb1a976585624177ef3e94bbb51b7edbc455b0905a92acb5e533d64031c6a5b62494fa4a60fa45c6386d0c3404f5c323cca98d6fd70dd606902458efd78cf12767a95ecb5f102ca7817260ed5e05768ed234d98e369b1a202c1ad89bd23b556909cc472f3088dade860c5aac87d906195b42a997d318d688f9c9405dfd44eac0c7803d03da33c020183571b487ba5620260afd53483a19a482675027a358c866121169bb2faaaa5598505f7cc9123ac83742281711b7c72810c5664c2809d6b1b8890e32b6cde6533b328ea209c507aa0b28521c0143aa4e0ba12c043f44f8e12442c567ec7b642a47bdff3bd2d9b9f1f6ee8b61ba7daa7176cfc2f66bf77d40ee5c8587cd9d59a2a8e0d54d47195fbd9b1eea82232fa860219ca2406f29922bf737040bf46d32a9b3941ac1597821ae57df4eb3477c3bb0644b829cbd4247465020ec85c77318ca185f4bfd691fff3e3fbd97d463467b7d612e293ba7aff765f522ca1b4a6b0495d4e1305de37079d02be7380fff9fd53d944344df038368daf119f492567d3f3ab0f1d72da192883ad253909e81f85d35a3afb07d16e618b9661d1cff049ba3828b08cc811a0a9abbff44f707b8dda5d26963c7d3fc6d7962858d95b4fb07d2bf752f6e36be7386d985cfac7372fa2fb728e7ee1e714e4aef66123fa5be406dc3ef52a2f7d9f7eeb6f8130000ffff7556550c86140000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("schema", "./schema")
		b.SetResolver("kustomize.json", packr.Pointer{ForwardBox: gk, ForwardPath: "012ad0df3dead178c5e342799d91280a"})
	}()

	return nil
}()
