// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "0b4107e573cf68c61af1d57560bb1128"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"012ad0df3dead178c5e342799d91280a": "1f8b08000000000000ffec584d8fd33010bde757585e8e5d0227a49ef782c40189235aadbccda4f56e629bf1185450ff3b4ad25671627b439b223e7ae9c1ceccbc797e3363f747c6187f65571ba8055f32be2132cb3c7fb25add76abaf35aef3024549b76fdee5ddda0d5f347605945249925a59be648d2bc6b8549644557d2230c745c6386d0d3401f4e313aca8b56fd70d6a0348126cef6bc6f8b3b3a46bf91dbce5b8a394b376af00bb42691ab4a3cd860384b2717b93f7b2ca2d81b9eb197a56bb851f41897a88d6436c09a55aa77d20682c00cf7573604f34a81fa4328ef892c57d0a44b1e58be1b624a8c75486d00c4d19e3b554eff7f66f07bbbb17c03f022a20b00fb550b2044b0fda5197c359b47c1332e9e351eb0ac40bc72c1ce93b3095de4e7135e2b48052b8aa81518aca4232948524dc4009b021f3a34d5114adb845f5b15f2d842e8de5aba85ca0aee614d12fa9a453441050b8960f0649af46a0a881009399c6888f707b6ee659046f2c5e2b2cef43842f4e22147cc93e079ad622de2a273496e9e5dbfbf03e1ba6774c2d8cb63711f66bf74783140f59cf3777668da280eb701a21be4e959369993a55fe99513053ebbdb6b5705bf33a962541cefe870d0ba102612f7ce338abc15c52bf4598a6d9e5e5d4f5bd761d89b38fc43f695a1987ebe4399f369f7f57f5ff4593caafbd40331968b839ef0fa0d6b4394af7e06c7cc5889450a074e2328b379c70334868de3f730b2b0c487eb2fd338cff4c48196701371385e71deefe9e744c60d1413968a38bd3fcb67142c486283dfc0778dae9853b7b7f4cf9e8fca7dd9c31fbafc560ccee723667c8de752f9ca5ba00b7fe252072f6c937f62efb190000ffffddc6e14949160000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("schema", "./schema")
		b.SetResolver("kustomize.json", packr.Pointer{ForwardBox: gk, ForwardPath: "012ad0df3dead178c5e342799d91280a"})
	}()

	return nil
}()
